version: '2'
services:
    txnmetadata-app:
        image: txnmetadata
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://txnmetadata-mysql:3306/txnmetadata?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    txnmetadata-mysql:
        extends:
            file: mysql.yml
            service: txnmetadata-mysql
